import {
  User,
  Course,
  Student,
  Lesson,
  CourseStudent,
  TeacherPayment,
  StudentPayment,
} from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@school.com",
    role: "admin",
  },
  {
    id: "2",
    name: "Ayşe Öğretmen",
    email: "teacher@school.com",
    role: "teacher",
  },
  {
    id: "3",
    name: "Mehmet Öğretmen",
    email: "mehmet@school.com",
    role: "teacher",
  },
  {
    id: "4",
    name: "Zeynep Öğretmen",
    email: "zeynep@school.com",
    role: "teacher",
  },
];

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Matematik Temelleri",
    courseNo: "CR001",
    teacherId: "2",
    totalLessons: 8,
    status: "active",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "İngilizce Konuşma",
    courseNo: "CR002",
    teacherId: "3",
    totalLessons: 10,
    status: "active",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    title: "Fizik Laboratuvarı",
    courseNo: "CR003",
    teacherId: "2",
    totalLessons: 6,
    status: "completed",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "4",
    title: "Kimya Temelleri",
    courseNo: "CR004",
    teacherId: "4",
    totalLessons: 12,
    status: "active",
    createdAt: new Date("2024-02-01"),
  },
];

export const mockStudents: Student[] = [
  {
    id: "1",
    name: "Ali Veli",
    phone: "+90 555 123 4567",
    email: "ali@email.com",
    isNew: true,
  },
  {
    id: "2",
    name: "Fatma Yılmaz",
    phone: "+90 555 234 5678",
    email: "fatma@email.com",
    isNew: false,
  },
  {
    id: "3",
    name: "Can Demir",
    phone: "+90 555 345 6789",
    email: "can@email.com",
    isNew: true,
  },
  {
    id: "4",
    name: "Zeynep Kaya",
    phone: "+90 555 456 7890",
    email: "zeynep@email.com",
    isNew: false,
  },
  {
    id: "5",
    name: "Ahmet Yıldız",
    phone: "+90 555 567 8901",
    email: "ahmet@email.com",
    isNew: true,
  },
  {
    id: "6",
    name: "Elif Özkan",
    phone: "+90 555 678 9012",
    email: "elif@email.com",
    isNew: false,
  },
];

export const mockCourseStudents: CourseStudent[] = [
  { courseId: "1", studentId: "1", hasPaid: true },
  { courseId: "1", studentId: "2", hasPaid: false },
  { courseId: "1", studentId: "3", hasPaid: true },
  { courseId: "2", studentId: "2", hasPaid: true },
  { courseId: "2", studentId: "3", hasPaid: true },
  { courseId: "2", studentId: "4", hasPaid: false },
  { courseId: "3", studentId: "1", hasPaid: true },
  { courseId: "3", studentId: "4", hasPaid: false },
  { courseId: "4", studentId: "5", hasPaid: true },
  { courseId: "4", studentId: "6", hasPaid: true },
];

export const mockLessons: Lesson[] = [
  {
    id: "1",
    courseId: "1",
    lessonNumber: 1,
    date: "2024-01-20",
    topic: "Doğal Sayılar",
    notes: "Öğrenciler konuyu iyi anladı",
    attendance: ["1", "2"],
    isCompleted: true,
    status: "completed",
  },
  {
    id: "2",
    courseId: "1",
    lessonNumber: 2,
    date: "2024-01-27",
    topic: "Tam Sayılar",
    notes: "Ek çalışma gerekli",
    attendance: ["1", "3"],
    isCompleted: true,
    status: "completed",
  },
  {
    id: "3",
    courseId: "1",
    lessonNumber: 3,
    topic: "Kesirler",
    notes: "",
    attendance: [],
    isCompleted: false,
    status: "planned",
  },
  {
    id: "4",
    courseId: "2",
    lessonNumber: 1,
    date: "2024-01-22",
    topic: "Basic Greetings",
    notes: "Great participation",
    attendance: ["2", "3"],
    isCompleted: true,
    status: "completed",
  },
  {
    id: "5",
    courseId: "2",
    lessonNumber: 2,
    date: "2024-01-29",
    topic: "Daily Conversations",
    notes: "Students need more practice",
    attendance: ["2", "4"],
    isCompleted: true,
    status: "completed",
  },
  {
    id: "6",
    courseId: "3",
    lessonNumber: 1,
    date: "2024-01-12",
    topic: "Laboratuvar Güvenliği",
    notes: "Temel güvenlik kuralları öğretildi",
    attendance: ["1", "4"],
    isCompleted: true,
    status: "completed",
  },
  {
    id: "7",
    courseId: "4",
    lessonNumber: 1,
    date: "2024-02-05",
    topic: "Atom Yapısı",
    notes: "Atom modelleri incelendi",
    attendance: ["5", "6"],
    isCompleted: true,
    status: "completed",
  },
];

export const mockTeacherPayments: TeacherPayment[] = [
  { teacherId: "2", courseId: "3", isPaid: true },
  { teacherId: "2", courseId: "1", isPaid: false },
  { teacherId: "3", courseId: "2", isPaid: false },
  { teacherId: "4", courseId: "4", isPaid: false },
];

export const mockStudentPayments: StudentPayment[] = [
  {
    studentId: "1",
    courseId: "1",
    amount: 500,
    date: new Date("2024-01-15"),
    isPaid: true,
  },
  {
    studentId: "2",
    courseId: "1",
    amount: 500,
    date: new Date("2024-01-16"),
    isPaid: false,
  },
  {
    studentId: "3",
    courseId: "1",
    amount: 500,
    date: new Date("2024-01-17"),
    isPaid: true,
  },
  {
    studentId: "2",
    courseId: "2",
    amount: 600,
    date: new Date("2024-01-20"),
    isPaid: true,
  },
  {
    studentId: "3",
    courseId: "2",
    amount: 600,
    date: new Date("2024-01-21"),
    isPaid: true,
  },
  {
    studentId: "4",
    courseId: "2",
    amount: 600,
    date: new Date("2024-01-22"),
    isPaid: false,
  },
];
